plugins/opa-wrapper/src/catalog-policies/policies.ts, plugins/opa-wrapper/src/opa-client/opaClient.ts, plugins/opa-wrapper/types.ts, policy/catpolicy.rego
=> Updated OPA Wrapper for Type Safety

plugins/opa-wrapper/src/opa-evaluator/opaPermissionEvaluator.ts, policy/catpolicy.rego
Updated policy.
Updated Input fields.
=> Updating Wrapper

plugins/opa-wrapper/src/opa-evaluator/opaPermissionEvaluator.ts, plugins/opa-wrapper/types.ts, policy/catpolicy.rego
Trying out dynamically adding `catalogConditions`
=> Opa work 3

plugins/gitlab-runners/package.json, plugins/gitlab-runners/src/components/RunnerCardComponent/RunnerCard.tsx, plugins/gitlab-runners/src/components/RunnerCardComponent/types.ts, plugins/gitlab-runners/src/types.ts
=> Gitlab runner plugin patch

catalog-info.yaml, example-policies/example_catpolicy.rego
Updated `catalog-info.yaml` and also updated the example policy.
=> Updating Catalog-info

CODE_OF_CONDUCT.md, plugins/opa-backend/README.md
=> Updated Wrapper Docs

plugins/opa-backend/src/service/router.ts, plugins/opa-entity-checker/src/components/OpaMetadataAnalysisCard/OpaMetadataAnalysisCard.test.tsx, plugins/opa-entity-checker/src/components/OpaMetadataAnalysisCard/OpaMetadataAnalysisCard.tsx, plugins/opa-permissions-wrapper/src/opa-client/opaClient.ts, plugins/opa-permissions-wrapper/src/permission-handler/permissionHandler.ts
Refactored the way we log some of the info from the OPA plugins.
=> Refactored some of the logging messages

plugins/opa-backend/README.md, plugins/opa-entity-checker/README.md, plugins/opa-permissions-wrapper/README.md
Updated README's for OPA plugins.
=> Updated Readmes for OPA Plugins

README.md, packages/app/src/components/catalog/EntityPage.tsx, plugins/dev-quotes-homepage/README.md, plugins/dev-quotes-homepage/package.json, plugins/dev-quotes-homepage/src/components/QuotesCardComponent/DevQuotesCard.test.tsx, plugins/dev-quotes-homepage/src/components/QuotesCardComponent/DevQuotesCard.tsx, plugins/dev-quotes-homepage/src/components/QuotesCardComponent/index.ts, plugins/dev-quotes-homepage/src/plugin.ts
Updated the docs for the plugins. Made some small naming changes.
=> Docs updates, small changes

plugins/opa-backend/package.json, plugins/opa-backend/src/service/router.ts, plugins/opa-entity-checker/README.md, plugins/opa-entity-checker/package.json, plugins/opa-entity-checker/src/api/types.ts, plugins/opa-entity-checker/src/components/OpaMetadataAnalysisCard/OpaMetadataAnalysisCard.tsx
Some updates to the OPA Entity checker plugin.
Mostly refactoring.
=> OPA entity checker update

packages/app/package.json, plugins/dev-quotes-homepage/package.json, yarn.lock
Small Patch on the dev quotes card to rebuild it to use `DevQuotesCard` and not `QuotesCard`
=> tiny patch

packages/app/package.json, packages/backend/package.json, plugins/dev-quotes-homepage/README.md, plugins/dev-quotes-homepage/package.json, plugins/dev-quotes-homepage/src/components/QuotesCardComponent/DevQuotes.test.tsx, plugins/dev-quotes-homepage/src/components/QuotesCardComponent/DevQuotes.tsx, plugins/dev-quotes-homepage/src/components/QuotesCardComponent/index.ts, plugins/dev-quotes-homepage/src/plugin.ts, plugins/dev-quotes-homepage/src/quotes.ts, yarn.lock
Removed a couple of quotes that could be considered offensive.
Updated it to remove the card, the card was making it look weird as a quote.
=> Small Patch

plugins/opa-permissions-wrapper/src/permission-evaluator/opaEvaluator.ts
For now, I have removed some logging from the evaluator as it was a bit too much. Need to think about it a bit more.
=> Removed some logging from Evaluator

package.json, plugins/backstage-opa-backend/package.json, plugins/backstage-opa-permissions-wrapper/package.json, yarn.lock
Updated and removed some dependencies.
=> updating and removing some old dependencies

plugins/backstage-opa-backend/src/service/router.test.ts, plugins/backstage-opa-backend/src/service/router.ts
Adds some better logging to the OPA Backend plugin, it will send a response to the front-end when input is missing or config settings are not set.
=> Better Logging in OPA Backend

README.md, docs/example-inputs-outputs.md, docs/opa-plugins-architecture.md
Adds some architecture type images to help understand how the flow works.
- Related Issue #105
- Closes #105 
N/A
=> Closes #105, adds architecture pictures to the plugin

plugins/backstage-opa-backend/package.json, plugins/backstage-opa-permissions-wrapper/package.json, yarn.lock
Updates release version and published to NPM.
=> OPA backend 1.2.3, OPA Perm Wrapper 0.4.1

example-opa-policies/entity-checker/entity_checker.rego, plugins/backstage-opa-entity-checker/README.md, plugins/backstage-opa-entity-checker/src/api/types.ts, plugins/backstage-opa-entity-checker/src/components/OpaMetadataAnalysisCard/OpaMetadataAnalysisCard.test.tsx, plugins/backstage-opa-entity-checker/src/components/OpaMetadataAnalysisCard/OpaMetadataAnalysisCard.tsx
Uses some fancy react stuff to optimize a bit, also refactoring the code a bit more as things have changed since I made it.
- Closes #
=> Refactoring the card and plugin a bit

plugins/backstage-opa-entity-checker/package.json, plugins/backstage-opa-entity-checker/src/components/OpaMetadataAnalysisCard/OpaMetadataAnalysisCard.tsx, yarn.lock
Updates deps, a small change to the coloring of the CHIP.
N/A
- Closes #
N/A
=> small refactor, fixing deps

.gitignore, example-opa-policies/README.md
Adds some of the default catalog rules from the catalog to construct conditional descisions.
- Related Issue #127 
- Closes #127 
N/A
=> Adding some of the existing conditional rules from the catalog.

plugins/permission-backend-module-opa-wrapper/package.json, tsconfig.json, yarn.lock
Node-fetch was on the wrong version causing the backend to crash.
N/A
- Closes #
N/A
=> updated nodefetch to the supported version

README.md, app-config.yaml, docs/opa-plugins-architecture.md, example-opa-policies/rbac/rbac_policy.rego, plugins/permission-backend-module-opa-wrapper/README.md, plugins/permission-backend-module-opa-wrapper/src/opa-client/opaClient.test.ts, plugins/permission-backend-module-opa-wrapper/src/opa-client/opaClient.ts, plugins/permission-backend-module-opa-wrapper/src/permission-evaluator/opaEvaluator.test.ts, plugins/permission-backend-module-opa-wrapper/src/permission-evaluator/opaEvaluator.ts, plugins/permission-backend-module-opa-wrapper/src/types.ts
Changes the way we evaluate policies, we move to using entrypoints which is discussed in #143 
- Related Issue #143 
- Closes #143 
N/A
=> Changes the way we evaluate policies to using entrypoints

plugins/permission-backend-module-opa-wrapper/README.md
=> minor rewording

plugins/backstage-opa-backend/README.md, plugins/backstage-opa-backend/config.d.ts, plugins/backstage-opa-backend/package.json
Updates the package ready for a release. And updates some old docs.
- Closes #
_Please replace this line with instructions on how to test your changes, a note
on the devices and browsers this has been tested on, as well as any relevant
images for UI changes._
=> creating release for OPA Backend Plugin

plugins/permission-backend-module-opa-wrapper/src/module.ts, plugins/permission-backend-module-opa-wrapper/src/opa-client/opaClient.test.ts, plugins/permission-backend-module-opa-wrapper/src/opa-client/opaClient.ts, plugins/permission-backend-module-opa-wrapper/src/permission-evaluator/opaEvaluator.test.ts, plugins/permission-backend-module-opa-wrapper/src/permission-evaluator/opaEvaluator.ts, plugins/permission-backend-module-opa-wrapper/src/policy.ts
We where using the wrong(?) Logger service, instead we should have used the core logger which is `LoggerService` to print debug logs.
- Closes #
_Please replace this line with instructions on how to test your changes, a note
on the devices and browsers this has been tested on, as well as any relevant
images for UI changes._
=> Fixes debug logging in the plugin

plugins/backstage-opa-backend/CHANGELOG.md, plugins/backstage-opa-backend/package.json, plugins/backstage-opa-entity-checker/CHANGELOG.md, plugins/backstage-opa-entity-checker/README.md, plugins/backstage-opa-entity-checker/package.json
Releases updates for OPA Backend and OPA Entity Checker Plugins
- Closes #
=> Releasing OPA Backend and OPA Entity Checker Plugins

README.md, example-opa-policies/README.md, example-opa-policies/entity_checker.rego, example-opa-policies/rbac_policy.rego
Updating the Docs to be a bit more up to date with how things have changed recently with the plugins.
=> Updating Docs

plugins/backstage-opa-backend/package.json, plugins/backstage-opa-entity-checker/package.json
=> fixes wrong url in the package json

plugins/backstage-opa-backend/README.md, plugins/backstage-opa-entity-checker/README.md, plugins/permission-backend-module-opa-wrapper/README.md
Updates docs, opa-backend had a dead link in it and removed the instructions for the old backend as most users should now be on the NEW backend system.
- Closes #
=> Updates Readme's

plugins/backstage-opa-backend/CHANGELOG.md, plugins/backstage-opa-backend/README.md, plugins/backstage-opa-backend/package.json
Releases new route in the backend plugin.
- Closes #
=> Release OPA Backend

plugins/backstage-opa-policies/src/api/types.ts
Removes some un-used types.
- Closes #
=> removes unused types

.eslintignore, .github/labeler.yml, .github/pull_request_template.md, .github/workflows/labeler-workflow.yaml, .prettierignore
- Closes #
_Please replace this line with instructions on how to test your changes, a note
on the devices and browsers this has been tested on, as well as any relevant
images for UI changes._
=> add labeler update pull request template

plugins/backstage-opa-entity-checker/package.json
Bumps `entity-checker` plugin.
=> [RELEASE] Entity Checker Plugin

plugins/permission-backend-module-opa-wrapper/package.json
Bumps the Permission Wrapper Plugin
=> [RELEASE] Permission Wrapper

plugins/backstage-opa-backend/package.json
=> [RELEASE] OPA Backend

plugins/backstage-opa-policies/package.json
=> [RELEASE] OPA Policies 

examples/entities.yaml, packages/app/src/App.tsx, packages/app/src/components/Root/Root.tsx, policies/rbac_policy.rego
=> Doing a bit of chore work and dusting

.eslintignore, .prettierignore, _config.yml
Trying to set up a docs site for the plugin.
N/A
=> Setting up Github Pages

docs/_sidebar.md
Adds an intro page to the docsify content.
If applicable, please link any related issues. Use "Closes" keyword to automatically close the issue on PR merge.
N/A
=> Docsify Introduction Page

.github/workflows/release.yml
Adds a release workflow to work with Changesets
=> Release Changeset Workflow

packages/app/src/components/Root/Root.tsx
Old un-used mui icon that should have been removed.
If applicable, please link any related issues. Use "Closes" keyword to automatically close the issue on PR merge.
Closes #<issue_number>
=> Remove MUI Icon from Root.tsx

README.md, docs/opa-permissions-wrapper-module/introduction.md, plugins/backstage-opa-backend/README.md, plugins/permission-backend-module-opa-wrapper/README.md
Small docs change before publishing.
Closes #<issue_number>
=> Small docs update before release

README.md, docs/opa-permissions-wrapper-module/introduction.md, plugins/permission-backend-module-opa-wrapper/README.md
Adds a reference to [platt-policy-template](https://github.com/ap-communications/platt-policy-template) (thanks @apc-kamezaki !) to the docs!
N/A
=> Adds platt-policy-template to the docs!

packages/backend/src/index.test.ts
Don't need this file anymore.
N/A
=> Removes Uneeded FIle

.github/workflows/main.yaml, package.json
Please provide a brief summary of your changes and the problem they solve.
If applicable, please link any related issues. Use "Closes" keyword to automatically close the issue on PR merge.
Closes #<issue_number>
=> Add CodeCov

docs/index.html
Homepage of docs site returns 404 at the moment, needs to be set explicitly in the index.html
If applicable, please link any related issues. Use "Closes" keyword to automatically close the issue on PR merge.
Closes #<issue_number>
=> Fix 404 on docs homepage

.github/workflows/test.yaml
=> fixing codecov

plugins/backstage-opa-backend/package.json
=> Release Prep!

package.json, plugins/backstage-opa-backend/README.md, yarn.lock
=> Fixing dead URLS!

.changeset/wild-glasses-drop.md, plugins/backstage-opa-policies/src/components/OpaPolicyComponent/OpaPolicyComponent.test.tsx, plugins/backstage-opa-policies/src/components/OpaPolicyComponent/OpaPolicyComponent.tsx
=> Adds Rego Syntax Highlighting to the card

README.md, docs/home/home.md, docs/opa-permissions-wrapper-module/inputs-and-outputs.md
Fixes some confusion in the docs
---
=> fixes some typos and inconsistencies in docs

docs/opa-permissions-wrapper-module/example-rbac-policy.md, policies/catalog.rego, policies/rbac_policy.rego, policies/scaffolder.rego
=> dynamic policy setup

policies/rbac_policy.rego
=> remove incorrect import to http_rules

plugins/backstage-plugin-opa-entity-checker-processor/package.json, plugins/opa-demo-backend/package.json, plugins/opa-frontend-demo/package.json
=> adds missing deps from the backstage cli repo fix command

plugins/backstage-plugin-opa-entity-checker-processor/package.json
=> patch to add missing deps

.changeset/cuddly-clouds-joke.md
=> release prep

.github/workflows/lint-and-format.yaml, .github/workflows/test.yaml, .github/workflows/welcome.yaml
Adds more fine grained access controls to the workflows
Best practises
NA
---
=> Add permissions to GitHub workflows for enhanced access control
